In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-0.7924569 , -0.73591848,  0.49293568, -1.43898969,  0.88506828,
        0.15567244,  0.11319865,  0.95105484,  0.40774101,  0.81008322])

In [7]:
B = np.random.randn(10)
B

array([-0.64764384, -0.11669372,  1.04825165,  1.73234448, -0.88786339,
        0.69531673,  0.45645684, -1.40559031,  1.39594984,  0.41839484])

In [9]:
C = np.random.randn(10)
C

array([ 0.74634066,  0.05214007, -0.15626417,  0.83278735, -1.1819479 ,
        0.48368726, -1.72344802, -0.17168249,  0.18019038, -0.54540134])

In [12]:
# Binary functions
np.add(A,B)

array([-1.44010074, -0.85261219,  1.54118733,  0.2933548 , -0.00279511,
        0.85098916,  0.56965549, -0.45453547,  1.80369085,  1.22847805])

In [14]:
np.maximum(A,B)

array([-0.64764384, -0.11669372,  1.04825165,  1.73234448,  0.88506828,
        0.69531673,  0.45645684,  0.95105484,  1.39594984,  0.81008322])